name: update-oracle

run-name: Poking the volatility oracle

on:
  workflow_dispatch:
  schedule:
  - cron: '23 */6 * * *'

jobs:
  send-txn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: build
        run: forge build
      - name: run
        env:
          RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
          RPC_URL_OPTIMISM: ${{ secrets.RPC_URL_OPTIMISM }}
          RPC_URL_ARBITRUM: ${{ secrets.RPC_URL_ARBITRUM }}
          RPC_URL_BASE: ${{ secrets.RPC_URL_BASE }}
          RPC_URL_LINEA: ${{ secrets.RPC_URL_LINEA }}
          RPC_URL_SCROLL: ${{ secrets.RPC_URL_SCROLL }}
          PRIVATE_KEY_UPDATE_ORACLE: ${{ secrets.PRIVATE_KEY_UPDATE_ORACLE }}
        run: |
          timeout -k 120s 120s forge script script/UpdateOracle.s.sol:UpdateOracleScript --chain optimism --rpc-url optimism -vv --broadcast &
          timeout -k 120s 120s forge script script/UpdateOracle.s.sol:UpdateOracleScript --chain arbitrum --rpc-url arbitrum -vv --broadcast &
          timeout -k 120s 120s forge script script/UpdateOracle.s.sol:UpdateOracleScript --chain base --rpc-url base -vv --broadcast &
          timeout -k 120s 120s forge script script/UpdateOracle.s.sol:UpdateOracleScript --chain linea --rpc-url linea -vv --broadcast &
          timeout -k 120s 120s forge script script/UpdateOracle.s.sol:UpdateOracleScript --chain scroll --rpc-url scroll -vv --broadcast &
          wait
