name: update-oracle

run-name: Poking the volatility oracle

on:
  workflow_dispatch:
  schedule:
  - cron: '30 * * * *'

jobs:
  send-txn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: build
        run: forge build
      - name: run
        env:
          RPC_URL_OPTIMISM: ${{ secrets.RPC_URL_OPTIMISM }}
          RPC_URL_ARBITRUM: ${{ secrets.RPC_URL_ARBITRUM }}
          RPC_URL_BASE: ${{ secrets.RPC_URL_BASE }}
          PRIVATE_KEY_UPDATE_ORACLE: ${{ secrets.PRIVATE_KEY_UPDATE_ORACLE }}
        run: forge script script/UpdateOracle.s.sol:UpdateOracleScript --broadcast
